### ISSUE TITLE
ofexport can't list all my folders 

### ISSUE THREAD

**Issue by dalemanthei** [psidnell/ofexport#9]
I think maybe I have a corrupted db but I'm at a loss on ideas to fix it.  I'm using OmniFocus 2 with a database that migrated with me through the various betas of OmniFocus 2.

Only some of my folders are seen but many are not.  I get the following trace back in terminal when trying to run ofexport without any parameters:

```
Traceback (most recent call last):
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/ofexport.py", line 239, in <module>
    m.generate(out, root_project, root_context, project_mode, template_dir, type_config)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/plugin_text.py", line 24, in generate
    format_document (subject, visitor, project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/fmt_template.py", line 166, in format_document
    traverse_list (formatter, root.children, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 260, in traverse_list
    traverse (visitor, item, ignore_marked=ignore_marked, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 265, in traverse
    traverse_folder (visitor, item, ignore_marked=ignore_marked)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 319, in traverse_folder
    traverse_list (visitor, folder.children, ignore_marked=ignore_marked)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 260, in traverse_list
    traverse (visitor, item, ignore_marked=ignore_marked, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 270, in traverse
    traverse_project (visitor, item, ignore_marked=ignore_marked, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 307, in traverse_project
    traverse_list (visitor, project.children, ignore_marked=ignore_marked, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 260, in traverse_list
    traverse (visitor, item, ignore_marked=ignore_marked, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 272, in traverse
    traverse_task (visitor, item, ignore_marked=ignore_marked, project_mode=project_mode)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/treemodel.py", line 291, in traverse_task
    visitor.begin_task (task)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/fmt_template.py", line 97, in begin_task
    self.update_attribs(task, 'task')
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/fmt_template.py", line 147, in update_attribs
    attribs = self.template.attrib_map_builder.get_values (item)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/attrib_convert.py", line 91, in get_values
    value = conversion.value (x, self.type_fns)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/attrib_convert.py", line 49, in value
    value = type_fns[self.type] (value)
  File "/Users/manthei/Dropbox/scripts/ofexport/src/main/python/attrib_convert.py", line 63, in <lambda>
    self.type_fns['date'] = lambda x: x.strftime(self.date_format)
ValueError: year=800 is before 1900; the datetime strftime() methods require year >= 1900
```

Any thoughts on how I can understand what is broken and fix it?  I'm trying to come up with a query that can find the tasks with the offending date prior to 1900 but no joy so far.

**Comment by psidnell** [comment]
It looks like one of the dates in your of database is set to 800AD, around the time Scotland was created and the Vikings were rampaging across Europe.

Do you have any very old TODO's like:
- "Build Longboat"
- "Sharpen Broadsword"
- "Pillage coastal communities"

:-)

It looks like Omnifocus allows dates to be set very far in the past (I just tried), so it's arguably perfectly valid - but has deeply offended the python date library.

Your DB is probably OK, but might you have typed in a pre-industrial start/due/completed date somewhere? It might be as simple as searching for the item with the oldest start/due/completed date and updating that to be, say, during the reign of King Edward VII.

**Comment by psidnell** [comment]
Only just spotted your comment at the bottom of the trace:

> Any thoughts on how I can understand what is broken and fix it? I'm trying to come up with a query that can find the tasks with the offending date prior to 1900 but no joy so far.

So you're ahead of me. I'd try and get Omnifoocus to tell you first, create a view that shows all your tasks/projects and try sorting by due, completed or start - it might just show up like that.

**Comment by dalemanthei** [comment]
It took a while but I found a workaround.  After some more experimentation I started to think that the db that ofexport was reading was not the same one my current version of OmniFocus was reading.  Basically because the last task output by ofexport could not be found via the OmniFocus GUI or grepping of the caches, etc.

I uninstalled OmniFocus 2, used spotlight to find all db and cache files and deleted them.  After a fresh install of OmniFocus 2 with a default db, ofexport was still showing me the same error on the same nonexistent task.

What finally fixed it was some tinkering with the ofexport.json file.  After a lot of experimentation, i found that the following in the ofexport.json would yield the correct results:

```
"db_search_path": [
        "/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2"
], 
```

My database is actually located at 

```
/Users/manthei/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Application Support/OmniFocus/OmniFocus.ofocus
```

I'm running latest Mavericks with a Omni store version of OmniFocus.

**Comment by psidnell** [comment]
I need to make sure I've added all the paths for OF2 (MAS & non MAS to the latest build).
